### ISSUE TITLE
Clarify Fib/Lucas Exercise wording

### ISSUE THREAD

**Issue by natasha-aleksandrova** [UWPCE-PythonCert/PythonCertDevel#105]
feedback based from student questions

----

suggesting to change 

`The function should return the nth value in the fibonacci series`

to 

`The function should return the nth value in the fibonacci series (starting with zero index)`

same for lucas directions

**Comment by PythonCHB** [comment]
Done.

Though that won't update the version in Canvas -- are you using the Canvas version or the gitHub published version?? (or EdX??)

Also -- you could do this kind of thing as a PR is you like:

It's here:

https://github.com/UWPCE-PythonCert/PythonCertDevel/blob/master/source/exercises/fib_and_lucas.rst

**Comment by natasha-aleksandrova** [comment]
Thanks!

I tried to create a branch for PR but didnt look like I had permissions. I probably could have forked the repo and do the PR that way.

And this is for EdX platform, which I have permissions to edit content there.
