### ISSUE TITLE
Add code reviewing rubric.

### ISSUE THREAD

**Issue by PythonCHB** [UWPCE-PythonCert/PythonCertDevel#129]
We could use a guideline for reviewing students' work -- a list of things to look for.

Here's a start:

## Logic issues:
 - Is the basic logic correct? 
 - Will it handle edge cases properly?
 - Is is using appropriate data types?

## Pythonicity:

Is the code Pythonic?

 - looping through a sequence  rather than indexing
 - EAFTP Exception handling
 - ...

## Style Issues
 - PEP 8 compliance
 - variable names:
    - one letter names only for index vaiables etc
    - verbs for functions. methods
    - nouns for objects
    - plural for sequences of objects.
    - ....

**Comment by PythonCHB** [comment]
Added a first daft in:

`source/for_instructors/code_review.rst`

published at:

https://uwpce-pythoncert.github.io/PythonCertDevel/for_instructors/code_review.html

**Comment by PythonCHB** [comment]
Needs review from other instructors:

@natasha-aleksandrova: could you give it a look over?

**Comment by natasha-aleksandrova** [comment]
will look a little later today

**Comment by natasha-aleksandrova** [comment]
The main list looks great; I think there should be an item for "Meeting main assignment requirements" which sometimes students do miss.

I am also interested in how will these correlate to actual "points" submissions.

<img width="478" alt="screen shot 2018-08-02 at 10 05 13 pm" src="https://user-images.githubusercontent.com/1928658/43625185-703da0a4-96a0-11e8-9e75-a36f79b10c29.png">


This is the current grading rubric in EdX which I am very not fond of 😄

I believe part of this revision was to update this EdX rubric to actually make sense for python course.

**Comment by PythonCHB** [comment]
I see -- I had not idea there was a Rubric like this in EdX!

No I know why you asked for a better one!

-- In Canvas, there's just a free-form place to put in how many points they received -- so I just put in 5 or 10 if they have "made a good faith effort".

If a student doesn't complete (enough of) the requirements, I give them a chance to update before I give them credit.

If you8 feel like it would be helpful to have a more defined "points" system then go ahead and suggest one.

BTW, I do intend to update the number of points each exercise is worth -- I found last time that students could "pass" without completing one (Or more!) of the major assignments at the end. I really don't think someone should pass if they haven't written any real OO code, for instance.

I'm very open to suggestions as to how to re-scale them. We can discuss in #33 

Once we know what we want, we can have Eliana update EdX

**Comment by natasha-aleksandrova** [comment]
Here is a swag at a rubric equivalent to what's in the EdX but more fitting for Python course.
<img width="611" alt="screen shot 2018-08-03 at 9 05 57 pm" src="https://user-images.githubusercontent.com/1928658/43672499-0a57a2e8-9764-11e8-8ed0-06bbc9beea05.png">


Ideally though I would prefer Points 1 (partial) and 3 (full points) to keep things simple but I am not sure what is possible from EdX point of view.

**Comment by PythonCHB** [comment]
In process via email, along with: #133

**Comment by natasha-aleksandrova** [comment]
resolved via a sync call this morning.
