### ISSUE TITLE
Update Setting Up Instructions

### ISSUE THREAD

**Issue by PythonCHB** [UWPCE-PythonCert/PythonCertDevel#130]
We need to make the "getting setup" instructions more clear. Some ideas:

1) It's a bit jumbled now, with multiple pages for the different steps etc -- we should turn that into a single, start to finish, clear set of instructions.

2) Even though there is a lot in common between platforms, it will probably be more clear if we duplicate, and have a full set for each platform -- so students can start with "if you are on Windows, do this" -- and then get a full set that is all about Windows.

Challenge:

I don't think we should require a particular setup -- for example,  if they have a programmer's Editor or IDE that they like, they should keep  using that. So we want to lay out what they need to be able to do, and then point them to suggested solution if they can't do that.

**Comment by natasha-aleksandrova** [comment]
couple questions:
* is there an existing document or is this brand new? (I'm not finding one)
* are these setup instructions for python only? or python + git?

**Comment by PythonCHB** [comment]
It's all there already -- but a bit scattered:

source/class_schedule/orientation.rst

which references various pages in:

source/supplemental/installing/

and 

source/supplemental/dev_environment/

you now see what I mean by "scattered".

**Comment by PythonCHB** [comment]
oh, and Python + git -- but I think the git one should be separate.

-CHB

**Comment by PythonCHB** [comment]
OK -- I"ve updated -- still needs to be reeiwed for Windows and Linux.

You can start here:

`source/modules/EnvironmentOverview.rst`

which then links to the pages in:

source/supplemental/installing/

It may be that the main page was not referenced in the EdX course, which would have made it hard...

**Comment by PythonCHB** [comment]
This is done -- though we need review of the Windows and Linux parts -- other Issues for those.
