### ISSUE TITLE
Update points for exercises

### ISSUE THREAD

**Issue by PythonCHB** [UWPCE-PythonCert/PythonCertDevel#133]
I found last time that students could "pass" without completing one (Or more!) of the major assignments at the end. I really don't think someone should pass if they haven't written any real OO code, for instance.

I'm very open to suggestions as to how to re-scale them.

**Comment by natasha-aleksandrova** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Grading Rubric](https://trello.com/c/edtwPFBG/6-grading-rubric)

**Comment by PythonCHB** [comment]
That seems to be a link to a Trello card I don't have access to -- should i?

**Comment by natasha-aleksandrova** [comment]
ignore trello links, its for my board and github integration auto-creates them.

**Comment by natasha-aleksandrova** [comment]
per meeting:

try to come up with point weight and rubric

**Comment by PythonCHB** [comment]
This is in process with Aliana in Google Docs and email....

**Comment by natasha-aleksandrova** [comment]
resolved via a sync call this morning.
