### ISSUE TITLE
More intro to trigrams

### ISSUE THREAD

**Issue by PythonCHB** [UWPCE-PythonCert/PythonCertDevel#135]
Online students need more detailed guidance..

**Comment by PythonCHB** [comment]
@natasha-aleksandrova: I just added a bunch to the trigram excercise. This is more or less what I do in class -- though with a bit more "exercise for the reader:

What do you think about the level of detail??

source/exercises/kata_fourteen.rst

**Comment by natasha-aleksandrova** [comment]
I think it's very detailed! This should certainly help students.

I did notice a few typos that should probably get probably get fixed since it is a feedback we often get from students 🙂

**Comment by PythonCHB** [comment]
Thanks,


I did notice a few typos that should probably get probably get fixed
>

I’ll give it another once over.

And feel free to fix any typos yourself when you find them :-)

-CHB
-- 
Christopher Barker, PhD

Python Language Consulting
  - Teaching
  - Scientific Software Development
  - Desktop GUI and Web Development
  - wxPython, numpy, scipy, Cython

**Comment by natasha-aleksandrova** [comment]
Good point - will correct as I see them!

**Comment by PythonCHB** [comment]
Did another proofread and typo fix -- so calling this done.
