### ISSUE TITLE
Review Windows Install instructions

### ISSUE THREAD

**Issue by PythonCHB** [UWPCE-PythonCert/PythonCertDevel#138]
Mostly this file:

source/supplemental/installing/python_for_windows.rst

But the rest could use a review too.

**Comment by natasha-aleksandrova** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Setting up Python - Windows](https://trello.com/c/qD2VBLFb/2-setting-up-python-windows)

**Comment by natasha-aleksandrova** [comment]
Ok so I reviewed python and git (gitbash) instructions.

I found a windows laptop and ran through the instructions - python install was a breeze, but I did run into few issues with gitbash + python. I have added some more information to the instructions based on my experience.

PR: https://github.com/UWPCE-PythonCert/PythonCertDevel/pull/147

**Comment by natasha-aleksandrova** [comment]
PR has been merged.
