### ISSUE TITLE
More explanation / tutorial for first Mailroom

### ISSUE THREAD

**Issue by PythonCHB** [UWPCE-PythonCert/PythonCertDevel#141]
We had some students comment:

"""
The mailroom assignment. Students had to conduct research external to the classroom and educate on programming aspect previously not learned in the classroom. More instruction on building functions and practice doing loops is required to be added.
"""

I think they should have the basics down by this point (this is not supposed to be their first programming experience).

But for the online class, some students may not know where to begin. So I suggest two "tutorials":

1) making an interactive command line loop: 
  - run through how to present a menu, take input, run code depending on the input, and go back to the menu.
 - I suggest NOT actually building the mailroom loop here, but rather, a similar loop that they can adapt to the mailroom problem. 

2) A bit about what data structure might make sense for the mailroom app.

I suggest a list of tuples: each tuple holds a name and list of donations. From my example solution:

```
donor_db = [("William Gates, III", [653772.32, 12.17]),
            ("Jeff Bezos", [877.33]),
            ("Paul Allen", [663.23, 43.87, 1.32]),
            ("Mark Zuckerberg", [1663.23, 4300.87, 10432.0]),
            ]
```

**Comment by natasha-aleksandrova** [comment]
PR for your review please: https://github.com/UWPCE-PythonCert/PythonCertDevel/pull/142

**Comment by natasha-aleksandrova** [comment]
Closing; above PR is merged.

**Comment by natasha-aleksandrova** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mailroom lessons 3](https://trello.com/c/obMTIIC4/3-mailroom-lessons-3)
