### ISSUE TITLE
Proofread install instructions

### ISSUE THREAD

**Issue by PythonCHB** [UWPCE-PythonCert/PythonCertDevel#144]
These pages:

https://github.com/UWPCE-PythonCert/PythonCertDevel/blob/c_1_revision/source/modules/EnvironmentOverview.rst

https://github.com/UWPCE-PythonCert/PythonCertDevel/blob/master/source/modules/EnvironmentOverview.rst

https://github.com/UWPCE-PythonCert/PythonCertDevel/blob/c_1_revision/source/supplemental/installing/python_for_mac.rst

These two: Linux and Windows need some review first....

https://github.com/UWPCE-PythonCert/PythonCertDevel/blob/c_1_revision/source/supplemental/installing/python_for_linux.rst

https://github.com/UWPCE-PythonCert/PythonCertDevel/blob/c_1_revision/source/supplemental/installing/python_for_windows.rst

**Comment by PythonCHB** [comment]
@natasha-aleksandrova: Is the Windows one ready for review? ( I think I see a "_new" version in the repo -- is that what we should work with?

@UWEditor, @DebalinaUW: Are we getting someone to test out the Linux install? or should we jsut proof this and move on?

**Comment by natasha-aleksandrova** [comment]
No I'm not done with Windows one (haven't really started it) - Was hoping to resolve the other pending tasks that in review before starting on this.

**Comment by natasha-aleksandrova** [comment]
@UWEditor : https://github.com/UWPCE-PythonCert/PythonCertDevel/blob/c_1_revision/source/supplemental/installing/python_for_windows.rst
