### ISSUE TITLE
Proofread: github tutorial updates and windows install for python/git 

### ISSUE THREAD

**Issue by natasha-aleksandrova** [UWPCE-PythonCert/PythonCertDevel#149]
See: https://github.com/UWPCE-PythonCert/PythonCertDevel/pull/147

Direct file links:
https://github.com/UWPCE-PythonCert/PythonCertDevel/blob/c_1_revision/source/modules/GitWorkflow.rst
https://github.com/UWPCE-PythonCert/PythonCertDevel/blob/c_1_revision/source/supplemental/installing/python_for_windows.rst

**Comment by PythonCHB** [comment]
@UWEditor -- I think this is done as well, yes?
