### ISSUE TITLE
Move lesson 3 tutorial to separate page

### ISSUE THREAD

**Issue by natasha-aleksandrova** [UWPCE-PythonCert/PythonCertDevel#150]

**Comment by PythonCHB** [comment]
And break up the initial mailroom exercise into separate pages. -- might as well do this all at once.

And why don't you do it in the `review_mailroom_oo` branch -- so that can be a branch for all the mailroom updates.

**Comment by natasha-aleksandrova** [comment]
I would prefer to work in a separate branch, not a fan of large PRs.  It looks like `review_mailroom_oo` is ready to merge.

**Comment by natasha-aleksandrova** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Split up mailroom into separate files.](https://trello.com/c/6nBv6jn1/10-split-up-mailroom-into-separate-files)

**Comment by natasha-aleksandrova** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Extract mailroom tutorial - plus add sorting.](https://trello.com/c/W8YrVzeJ/11-extract-mailroom-tutorial-plus-add-sorting)

**Comment by PythonCHB** [comment]
sure -- whatever works -- just make sure that @UWEditor  knows what to do.

Go ahead and merge ``review_mailroom_oo``  if you like.

**Comment by natasha-aleksandrova** [comment]
PR: #156
