### ISSUE TITLE
Lesson8: confusion over step 5

### ISSUE THREAD

**Issue by natasha-aleksandrova** [UWPCE-PythonCert/PythonCertDevel#186]
I just noticed this line:
`NOTE: wait on this one ‘till we learn about class methods..`
in step 5:
https://uwpce-pythoncert.github.io/PythonCertDevel/exercises/circle_class.html#step-5

This caused confusion with students whether they should implement this step or not.

Even though this is listed as one of the goals:
```
You will use:

properties.
a bunch of “magic methods”.
a classmethod (after you’ve learned about them…).
```

is step 5 required? 
 if yes then the note should be removed or clarified
 if no, then step 5 should be removed

**Comment by natasha-aleksandrova** [comment]
@ChrisBarker-NOAA

**Comment by natasha-aleksandrova** [comment]
Looks like this can be linked to this doc: https://uwpce-pythoncert.github.io/PythonCertDevel/modules/StaticAndClassMethods.html in that NOTE

**Comment by natasha-aleksandrova** [comment]
<img width="284" alt="Screen Shot 2019-06-05 at 6 11 56 PM" src="https://user-images.githubusercontent.com/1928658/59000012-726fa980-87bd-11e9-87c1-1d3822914523.png">
the site doesn't mention class methods in the outline, but link is included as part of the required reading but not mentioned again in the videos.

**Comment by PythonCHB** [comment]
I just noticed that last week -- thanks for the prod to fix it.

It is in required reading, so I've removed that note, and added one "this would be a good use of classmethod": bce41c45765708d82
