### ISSUE TITLE
No index.html in the gh-pages branch root.

### ISSUE THREAD

**Issue by PythonCHB** [UWPCE-PythonCert/PythonCertDevel#2]
It looks like the gh-pages branch was re-structured to put everything inside an html dir.

However, gh-pages expectes to find an index.html file at the root in order to serve up the docs.

Maybe there is a way to re-direct? or???

@rriehle: It looks like you updated this -- any ideas?

Also -- will the build_gh_pages.sh script still do the right thing?

**Comment by rriehle** [comment]
Yep, @PythonCHB that was most likely me. So the gh-pages/github.io site is down at present. I'm not sure what exactly the problem is... perhaps we can resolve it together on Wednesday. My guess is that it's working for you via the build script... but that when I run it somehow the rendering to github.io gets clobbered. Bah.

**Comment by PythonCHB** [comment]
It's actually not down, you just need to tack the "html" on the end of the URL.

I thought you did that on purpose, so I've been adapting to it...

https://uwpce-pythoncert.github.io/PythonCertDevel/html/index.html

Di you run the build_gh_pages script to build it? If so -- really weird. Though I adapted it to do it this way now. So if we just figure out a redirect...

**Comment by rriehle** [comment]
Yes... I've been using build_gh_pages. And I seem to remember us running into this before... an html folder as essentially useless in the path. I'll take a look when I have time. Seems sorta dumb not to render the index.html directly into what is effectively the root of the github.io page... so I prefer your way.

**Comment by PythonCHB** [comment]
OK -- what in the world happened?

I thought you did it on purpose, so I actually updated teh script to keep doing it your way :-)

I'll put it back and see what the deal is....

**Comment by PythonCHB** [comment]
I have put build_gh_pages.sh back the way it was, and cleaned up teh gh-pages branch.

S it all should be good now.

But maybe comment out the commit and push from build_gh_pages before you run it, to make sure it doesn't do anything weird for you...
