### ISSUE TITLE
Assignment for the full gitHub process

### ISSUE THREAD

**Issue by PythonCHB** [UWPCE-PythonCert/PythonCertDevel#22]
I am curretnly working with a student in week 5, tryin got get them able to submit work via gitHub.

His configuration was not quite right.

So we should have a "must do" assignement ni week 1 that requires the full process:

git pull upstream master

git push

add a file

change a file

commit it

do a PR

etc.

This may "fall out" of them turning in their first assignment, but as we don't' have anything "graded" in the first week, maybe this should be it.

**Comment by PythonCHB** [comment]
Same as #26.

It's a maybe -- particularly since we may have to dump gitHub due to FERPA

**Comment by PythonCHB** [comment]
maybe later -- we'll see how the class goes.

**Comment by PythonCHB** [comment]
This is still a good idea if we can find the time to do it.

**Comment by PythonCHB** [comment]
@natasha-aleksandrova: from your experience with the online class -- do we need this? Or do they learn it when they first have to turn in something?

**Comment by natasha-aleksandrova** [comment]
Students do this via first PR with README and their initial student directory. Most of the students do this; but some skip it. I can't find where that part is in the docs or on the course website right now... but I think that part should be a required step. 

Might be worth reviewing direction on the site to make

**Comment by PythonCHB** [comment]
OK -- so I think we should make that first PR a requirement with points.

Do you think that would do it?

**Comment by natasha-aleksandrova** [comment]
I think so; If I ever find the place where they are told to do so, would be good to review if it needs more direction.

**Comment by natasha-aleksandrova** [comment]
Circling back on this.. So do I need to find where the student directory with README is mentioned and make sure it is worded as a required task? 

Or what else needs to be done on this one?

**Comment by PythonCHB** [comment]
yeah, I think finding that would be a good place to go -- use your judgment, I haven't tried to do any of this with an online class. -- doing it live with them in class has worked fine.

**Comment by natasha-aleksandrova** [comment]
👍 I will do some research on the placement.

**Comment by natasha-aleksandrova** [comment]
PR https://github.com/UWPCE-PythonCert/PythonCertDevel/pull/147

**Comment by natasha-aleksandrova** [comment]
PR has been merged.
