### ISSUE TITLE
Expand string formatting exercise

### ISSUE THREAD

**Issue by PythonCHB** [UWPCE-PythonCert/PythonCertDevel#45]
The string formatting exercise was designed to be done quickly in class. But if it's being used as a do on your own time exercise, it could be fleshed out -- made a bit longer, and provide better explanations.

It would be good to exercise the most commonly used formatters, and probably show both positional and keyword formatting as well.

**Comment by PythonCHB** [comment]
And add f-strings -- same formatting language, but new context....

**Comment by PythonCHB** [comment]
@milesak60: This might be a good one for you to work on. IF you have any time before your Holiday -- no internet -- such bliss!

**Comment by milesak60** [comment]
I'm a bit pushed for time but if I can have until Weds 12/27 I promise I'll do it. I can briefly work offline while away  and mail it from public hotspot if all else fails. You'd have it by 1800.

Andy Miles

________________________________

**Comment by PythonCHB** [comment]
You can have whatever time you need :-) -- just thought I'd make a suggestion for something to work on IF you do have time.

**Comment by milesak60** [comment]
Ok thanks it will be with you next week.
Enjoy the break if we don't chat again

Andy Miles

________________________________

**Comment by PythonCHB** [comment]
Looking good now -- Thanks Andy!
