### ISSUE TITLE
Text for exercise submission

### ISSUE THREAD

**Issue by PythonCHB** [UWPCE-PythonCert/PythonCertDevel#50]
the three sentence version to go into Canvas.

Coordinate with Joe and Christy

**Comment by PythonCHB** [comment]
Here is my email note:

Liz needs few sentence summary of how to submit assignments to put into Canvas, etc.

It would be good for it to be consistent among the three courses.

I have set up an example repo for a class:

https://github.com/UWPCE-PythonCert/DemoClassRepo

The idea is that for each "instance" of the class, the instructor would make a copy of this repo, and then everyone would be working with the same thing, and our instructions can be consistent other than the actual repo name.

I already made a video demonstrating how to create a new file, add it to git, commit, push, and do a PR. So ideally we don't change this structure much, but if any of you think it won't work for you, now is the time to make changes.

Here is the script of that video:

https://docs.google.com/document/d/1eB4UGdgdziG35cJ23qCAuIsICILeScuouDRrIqf4XM0/

Though not a lot there -- it was mostly live demo.

Here is what I propose for text:

Submission:

As always, put each new file (ex: mailroom.py) in your student directory in a new directory named for this lesson (ex: lesson03), and add it to your clone early. (git add the_file.py). Make frequent commits with good, clear messages about what you are doing and why.

When you are done, push your changes to your giHub fork (git push) and then go to the gitHub website and make a pull request.

[optional -- should we have them do this?]

After making your PR, copy the gitHub link to the PR, and put it in Canvas to let your instructor know that you've submitted your work.

-----

NOTE: when a student does a PR, the instructor(s) get an email, and they can easily go to gitHub and see whats been submitted. So having them put a link in Canvas is just and extra step.

-CHB

**Comment by JASchilz** [comment]
I'd say that the process is suitable for the types of assignments given in courses 1 and 2. For course 3, many of the assignments are more like projects which students can/do deploy to the internet. For these, I think it's appropriate for each student to work in their own repository.

For these, the instructions are roughly:
1. Fork the starter code into your own GitHub account.
2. Pull down to your machine.
3. Do the work.
4. Push up to your repo.
5. Submit a link in Canvas to your repo.
6. I grade and put their grade in Canvas.

For grading, I have a script that pulls down all of the students' work (just need their GitHub username plus the name of the week's repo) into a directory on my computer. I run some automated tests and also review the code, providing feedback as comments or revisions in a pull request.

What I like about your system is that it's easy for students to collaborate, see each others' work and solutions, and your comments and revisions: it's more of a group learning effort. What I like about my system is that it's closer to "real world" use of git, and removes the possibility of students accidentally stepping on eachothers' toes with commit conflicts.

**Comment by PythonCHB** [comment]
@JASchilz:

Good points, and I totally agree.

So let's go with my proposal (and current workflow) for course 1&2, and then in course 3, you guys can teach them how to make their own repos for their work.

This is a good progression anyway -- hopefully they will have gotten a tiny bit comfortable with git, by then, so it's time for them to learn how to use it on their own.

**Comment by PythonCHB** [comment]
done.
