### ISSUE TITLE
Need to change links to exercises and examples to downloads

### ISSUE THREAD

**Issue by codedragon** [UWPCE-PythonCert/PythonCertDevel#57]
Links from the documentation to python files in the exercises and examples directories need to be changed to downloads. For example in exercises/unit_testing.rst, there is a reference to the test_cigar_party.py file, which is currently in the examples/testing folder.

**Comment by PythonCHB** [comment]
Note that I"ve been putting the files themselves in the examples dir, and then doing a download link like so:

```
:download:`properties_example.py <../examples/Properties/properties_example.py>`]
```

**Comment by PythonCHB** [comment]
maybe some still broken, but mostly good.
