### ISSUE TITLE
Add more explanation to the mailroom 2 exercise

### ISSUE THREAD

**Issue by PythonCHB** [UWPCE-PythonCert/PythonCertDevel#6]
a bit more on what is meant by "write letter so to disk"

see the email list for text.

**Comment by natasha-aleksandrova** [comment]
I can come up with some more info but is there anything specific that should be called out? 

I haven't had a single student really struggle with it or have questions so don't really have context - the only issues I often see is not using `with` statement or students hardcoding file path that exists on their personal machine.

**Comment by PythonCHB** [comment]
maybe just a bit more clarity in what is being asked for.

i.e. one text file per person, names of file, where to put them, etc.

But if you haven't seen them having issues, then this can be a quick one!

**Comment by natasha-aleksandrova** [comment]
perfect - that helps.

**Comment by natasha-aleksandrova** [comment]
PR up: https://github.com/UWPCE-PythonCert/PythonCertDevel/pull/143

**Comment by natasha-aleksandrova** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mailroom - lesson4 - file writing](https://trello.com/c/aIwjs6r3/7-mailroom-lesson4-file-writing)

**Comment by natasha-aleksandrova** [comment]
merged.
