### ISSUE TITLE
Remaining work

### ISSUE THREAD

**Issue by pythonsavvy** [UWPCE-PythonCert/PythonCertDevel#66]
All of class 1 lessons reviewed. 8,9,10 seem light on material (in 10 there is nothing for me to review yet). I'll keep watch for when it is done. I will revisit all the classes to make sure any new material is reviewed, and to address the demo omissions where I can.  I will also test the code more extensively as time permits.

**Comment by PythonCHB** [comment]
yeah, 8,9,10 didn't get the attention they needed -- particularly 10.

I'll create issues and assign them to me and Rick.

**Comment by PythonCHB** [comment]
yup -- this is out of date.
