### ISSUE TITLE
Add a little more to the mailroom-OO

### ISSUE THREAD

**Issue by PythonCHB** [UWPCE-PythonCert/PythonCertDevel#68]
We can add a bit more to the Mailroom-OO assignemnt: probably as "extra optional features":

Using indexing to get a donor:

The_donor_db["a name"]

Making Donor objects sortable

... other nifty ideas?

**Comment by PythonCHB** [comment]
Maybe add using += to add a new donation:

a_donor += 2000

**Comment by PythonCHB** [comment]
We also need to enhance the instructions here -- we did do that last spring, but more review and maybe more instructions are in order.

**Comment by natasha-aleksandrova** [comment]
looks like this is the file to update:
https://github.com/UWPCE-PythonCert/PythonCertDevel/blob/master/source/exercises/mailroom-oo.rst

**Comment by PythonCHB** [comment]
That sounds great -- and the cli.py can have ALL the calls to `input` in it -- making it easier to say that `donor_collection.py` should have 100% test coverage.

(I called it `model.py` in my solution, but this is fine, too)

**Comment by natasha-aleksandrova** [comment]
awesome! thanks for the feedback, I will get started on making updates.

**Comment by PythonCHB** [comment]
and yes, that's the file :-)

**Comment by natasha-aleksandrova** [comment]
Have a PR for your review:
https://github.com/UWPCE-PythonCert/PythonCertDevel/pull/131

**Comment by natasha-aleksandrova** [comment]
closing this - PR was merged.

**Comment by natasha-aleksandrova** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mailroom OO](https://trello.com/c/cg3lsV1k/1-mailroom-oo)
