### ISSUE TITLE
Have "Extra Credit" portions in Exercises?

### ISSUE THREAD

**Issue by PythonCHB** [UWPCE-PythonCert/PythonCertDevel#7]
Should we have extra credit suggestions in the exercises?

It's not a graded course, so extra credit isn't the right term, but there are students that whip out the assignments quickly, and could use more of a challenge, or simply more to do.

This would only apply to the more challenging assignments, like trigrams or mailroom, etc.

We already do suggest that they can choose to get more complex, but we maybe should make specific suggestions.

**Comment by rriehle** [comment]
I like tiered exercises like we've discussed: easy/moderate/hard. Perhaps that's a better framing for a pass/fail course.

As to whether this is necessary or a nice to have... that's another topic. I'd love to do it on a regular basis if we had time to develop the exercises along these lines.

**Comment by PythonCHB** [comment]
OK -- I'm liking this. We'll need to go through at least the major exercises, and see where we can add some "For more challenge" components.

Certainly mailroom and trigrams, and html renderer...

**Comment by PythonCHB** [comment]
We have some of this already -- so good to go.
