### ISSUE TITLE
remove out of date markup

### ISSUE THREAD

**Issue by PythonCHB** [UWPCE-PythonCert/PythonCertDevel#72]
there is a bunchof markup in there left over from when we were doing hieroglyph slides.

stuff like:

```
.. rst-class:: medium
```

we can jsut get rid of that...

@milesak60: might as well clean this kind of stuff up as you go.

And/or do one commit that is nothing but removing this kind of thing -- some grepping should make that doable.

**Comment by PythonCHB** [comment]
oh and ``.. nextslide::`` is obviously not needed when you're not making slides...

**Comment by milesak60** [comment]
I'll remove all the markup in one go later this week

Andy Miles

________________________________

**Comment by PythonCHB** [comment]
Perfect

**Comment by milesak60** [comment]
Completed 12/21/17
