### ISSUE TITLE
When to make Solutions Available?

### ISSUE THREAD

**Issue by PythonCHB** [UWPCE-PythonCert/PythonCertDevel#8]
This is something that I've struggled with for ages.

Some students want to have solutions available early, so they have something to consult when they get stuck.

Others would rather not be tempted to look, and want to be "forced" to figure it out for themselves.

This is perhaps something that each instructor and modality could do differently, but I'm wondering what others think?

NOTE: I am taking a poll, right now, of the students in the fall 2017 class. People have come down on both sides so far -- we'll see when I get more feedback is there is an obvious preference.

Also -- if the assignments are "Graded" then maybe we can't make solutions available 'till after they have been submitted.

**Comment by rriehle** [comment]
1.  Put people in control of their own learning strategies and they will thrive. Prevent them from access to information and they may become frustrated and abandon the path.

2.  Progressive challenges are enough to facilitate growth. Providing support by way of solutions will assist those who are struggling and will not hurt those who are advancing on their own without assistance.

3.  We are all adults here.

I am completely unequivocal about this; there is no question in my mind. Let them have the solutions early and often.
