### ISSUE TITLE
Update text file parsing exercise

### ISSUE THREAD

**Issue by PythonCHB** [UWPCE-PythonCert/PythonCertDevel#83]
At the very least, we need to create a fake students and languaes list to parse.

Or just come up with another problem.

@rriehle, @summerela, @milesak60: any ideas?

**Comment by summerela** [comment]
I am pretty sure @rriehle had something like this already?

**Comment by PythonCHB** [comment]
I redid it with a fake students list:

https://uwpce-pythoncert.github.io/PythonCertDevel/exercises/file_lab.html

If anyone has a better idea, great, but for now we've got something.
