### ISSUE TITLE
Packages and Packaging module

### ISSUE THREAD

**Issue by pythonsavvy** [UWPCE-PythonCert/PythonCertDevel#88]
Based on https://uwpce-pythoncert.github.io/PythonCertDevel/modules/Packaging.html, looks like it could use more work. Happy to take that if so. Please assign to me if needed. It doesn't flow well I think.

**Comment by PythonCHB** [comment]
It does need work, but that's on the ticket for course 2.

I'll change the milestone.

**Comment by PythonCHB** [comment]
updated for the live class, but could still use some review.

**Comment by PythonCHB** [comment]
So is this all done in Course 2?

I would think we can we close #69 too -- unless we still need a deeper dive.
