### ISSUE TITLE
Update testing module

### ISSUE THREAD

**Issue by PythonCHB** [UWPCE-PythonCert/PythonCertDevel#9]
and the lab!

**Comment by PythonCHB** [comment]
Updated some, but maybe put even less in there about unittest -- it's just confusing at this point.

And maybe port Ned Batchelder's talk to pytest??

**Comment by natasha-aleksandrova** [comment]
going to work on this next.

**Comment by natasha-aleksandrova** [comment]
@PythonCHB just to confirm, the plan is to update mailroom.rst file (bottom unit testing section) with more detail on how to unit test mailroom and encourage use of pytest - is that accurate?

**Comment by natasha-aleksandrova** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mailroom Unit Testing](https://trello.com/c/O2VNk6Ak/4-mailroom-unit-testing)

**Comment by natasha-aleksandrova** [comment]
progress so far:
https://github.com/UWPCE-PythonCert/PythonCertDevel/blob/c_1_rev_mailroom_lesson6/source/exercises/mailroom.rst#guidelines-1

**Comment by PythonCHB** [comment]
looking good -- if you make a PR, I can comment on specific lines, but looking good so far.

one comment -- let's go straight to pytest -- some folks may want to use unittest, but I think we should keep it simple and only talk about pytest.

**Comment by natasha-aleksandrova** [comment]
ok will do.

**Comment by natasha-aleksandrova** [comment]
PR https://github.com/UWPCE-PythonCert/PythonCertDevel/pull/145

**Comment by natasha-aleksandrova** [comment]
PR is merged.
